# Generated by Django 6.0.3 on 2026-03-28 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_date',
        ),
        migrations.RemoveField(
            model_name='player',
            name='role',
        ),
        migrations.RemoveField(
            model_name='team',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='start_date',
        ),
        migrations.AddField(
            model_name='match',
            name='balls_in_over',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='non_striker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_non_striker', to='core.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='overs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='striker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_striker', to='core.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='total_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(default='Live', max_length=20),
        ),
    ]
