# Generated by Django 6.0.3 on 2026-03-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_match_match_date_remove_player_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='current_innings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='recent_balls',
            field=models.TextField(blank=True, default=''),
        ),
    ]
