# Generated by Django 6.0.3 on 2026-04-01 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_match_current_innings_match_recent_balls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='non_striker',
        ),
        migrations.RemoveField(
            model_name='match',
            name='status',
        ),
        migrations.RemoveField(
            model_name='match',
            name='striker',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_a',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_b',
        ),
        migrations.RemoveField(
            model_name='match',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='player',
            name='balls',
        ),
        migrations.RemoveField(
            model_name='player',
            name='runs',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tournament',
        ),
        migrations.AddField(
            model_name='match',
            name='current_batsman',
            field=models.CharField(default='Batsman', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='current_bowler',
            field=models.CharField(default='Bowler', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='target_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a_name',
            field=models.CharField(blank=True, default='Team A', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b_name',
            field=models.CharField(blank=True, default='Team B', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
