# Generated by Django 6.0.3 on 2026-04-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_match_team_a_match_team_b_match_tournament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='non_striker',
            field=models.CharField(default='Batsman 2', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='current_batsman',
            field=models.CharField(default='Batsman 1', max_length=100),
        ),
    ]
