# Generated by Django 6.0.3 on 2026-04-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_match_non_striker_alter_match_current_batsman'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='non_striker_balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='non_striker_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='striker_balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='striker_runs',
            field=models.IntegerField(default=0),
        ),
    ]
