# Generated by Django 6.0.3 on 2026-04-02 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_match_non_striker_balls_match_non_striker_runs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_result', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.match')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
