# Generated by Django 6.0.3 on 2026-04-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ballhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='recent_balls',
        ),
        migrations.AddField(
            model_name='player',
            name='balls_faced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='fours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='overs_bowled',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='runs_conceded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='runs_scored',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='singles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='sixes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wickets_taken',
            field=models.IntegerField(default=0),
        ),
    ]
