# Generated by Django 6.0.3 on 2026-04-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_match_is_finished_match_match_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='last_total_marker',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='toss_decision',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='toss_winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
